### ISSUE TITLE
WSS:// not working

### ISSUE THREAD

**Issue by RichardLGP5** [MediaMongrels-Ltd/LabVIEW-WebSockets-API#6]
Hello, Thanks for the great code. It works with echo server using ws, but not wss. 
<img width="743" alt="image" src="https://user-images.githubusercontent.com/34357597/81118115-ed6da280-8eed-11ea-84ad-b8900471af12.png">
Any suggestions?

**Comment by samsharp99** [comment]
Hi - I will have to test and check again but I believe this is because the wss echo server uses an outdated/insecure protocol (I think SSLv1) and this isn't supported by the SSL/TLS functions (it isn't possible to allow older/insecure protocols). This isn't an issue with the WebSockets library but a combination of only allowing secure protocols in the LabVIEW functions and the website running an older/insecure one.

**Comment by RichardLGP5** [comment]
Hi Sam,

Thanks for the prompt reply. I just found the link to https://github.com/MediaMongrels-Ltd/LabVIEW-Secure-WebSockets-Addon so will try that next.

Richard

**Comment by samsharp99** [comment]
Ah yes - for wss:// to work you need to use the add on package for LV2020 which adds support for it.
